services:
  - type: web
    name: pulsetransit-backend
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: "*"
